### ISSUE TITLE
1.14-1.16.1 compatibility pre 1.14 backport

### ISSUE THREAD

**Issue by contariaa** [Technici4n/advancements-debug#11]
hi, 
i tested your mod in 1.14 and it seemed to work perfectly fine (code also hasnt changed so i dont see why it wouldnt), if you want you could edit that in the modrinth release

i also made a backport for 1.12-1.13.2 (works with legacy fabric), if you want i can make a pullrequest so you can add it as an extra branch, it was just mapping changes bc of legacy fabric, code is the same

**Comment by Technici4n** [comment]
Hi, I just marked the CF and Modrinth as compatible with all the versions included in 1.14 - 1.19. However, I don't want to be supporting earlier versions, but feel free to do it yourself if you want. :)

**Comment by contariaa** [comment]
sounds good, do i have permission to upload it to modrinth as "Legacy Advancements Debug"? :)

**Comment by Technici4n** [comment]
Yes, go ahead! :)

**Comment by contariaa** [comment]
okidoki thanks!
