### ISSUE TITLE
Mod no longer works on 1.19.4.

### ISSUE THREAD

**Issue by Kichura** [Technici4n/advancements-debug#12]
[Dump](https://pastebin.com/raw/FJTshgdF) - And in GUI, Player will see "Invalid Player Data" in any world.

**Comment by Technici4n** [comment]
Minecraft 1.19.4 changed some advancement code, and fixed the bug that advdebug was fixing, hence advdebug is not needed anymore.

RIP 2020-2023 Advancements Debug

**Comment by Kichura** [comment]
was a fun ride then. F
