### ISSUE TITLE
1.19 & Modrinth

### ISSUE THREAD

**Issue by srnyx** [Technici4n/advancements-debug#6]
1. Can you update it to 1.19?
2. Can you upload it to [Modrinth](https://modrinth.com)?

**Comment by Technici4n** [comment]
1. Can you try the existing advancements debug in 1.19? It might work fine already.

2. Sure, why not. Will do once you've checked whether the existing build works in 1.19.

**Comment by srnyx** [comment]
> 1. Can you try the existing advancements debug in 1.19? It might work fine already.
> 2. Sure, why not. Will do once you've checked whether the existing build works in 1.19.

1. Yeah, it seems to work, but not really sure how to check to be 100% sure.
2. Thank you so much!!

**Comment by Technici4n** [comment]
1. Done
2. Will be available on https://modrinth.com/mod/advancements-debug after the modrinth team has reviewed it.
