### ISSUE TITLE
When Advancement Appear Log spam so much until crashed the console

### ISSUE THREAD

**Issue by ardissaps** [Technici4n/advancements-debug#7]
The game not crash but the console hang

https://paste.atlauncher.com/view/daf9bfa6-8a10-43c4-bac4-b7db20d12994

**Comment by Technici4n** [comment]
That's not caused by this mod. It's probably something else in your pack.

**Comment by ardissaps** [comment]
> That's not caused by this mod. It's probably something else in your pack.

Ah yes, it is [Advancement Plaque](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques). Sorry!

**Comment by ardissaps** [comment]
> That's not caused by this mod. It's probably something else in your pack.

Ah yes, it is [Advancement Plaque](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques). Sorry!
