### ISSUE TITLE
Idea for mod icon

### ISSUE THREAD

**Issue by yannick1124** [Technici4n/advancements-debug#8]
I saw your mod icon and thought I'll make something real quick. Use and edit this as much as you want, I don't need credit.

The only pre-existing asset in this image is the advancement badge, which I took from the Minecraft wiki, and it should be free to use for non-commercial projects like this.

![advancements_debug](https://user-images.githubusercontent.com/27208823/176982594-3c54ec8c-c4ac-40a7-a31c-4bf33a7795ce.png)

**Comment by Technici4n** [comment]
Looks great, thanks for the idea. ^^

**Comment by yannick1124** [comment]
you're welcome :)
